title: Ryan Chang
description: Fueled by coffee, driven by craft

author:
  name: Ryan Chang
  first_name: Yan Qian
  last_name: Chang
  email: ryancyq@gmail.com
  website: https://ryancyq.com

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-postcss-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/tagging

nav_pages:
  - blog/index.html
  - projects.md
  - resume.md
page_sub_title: false

social_links:
  - platform: github
    user_url: https://github.com/ryancyq
  - platform: linkedin
    user_url: https://linkedin.com/in/changyanqian/

tag_page_layout: tag
tag_page_dir: topic

collections:
  jobs:
  projects:
  education:
  posts:
    output: false
    permalink: /:collection/:categories/:year/:month/:day/:slug

paginate: 5
paginate_path: "/blog/:num/"
words_per_minute: 180

# Build Settings
timezone: Asia/Singapore
date_format: "%d-%b-%Y"
strict_front_matter: true
postcss:
  cache: false
markdown: kramdown
highlighter: rouge

exclude:
  - "*.js"
  - "*.json"

# SEO and Site Configuration
google_analytics: G-B3F2H65ZT2
seo:
  title: ryancyq
  description: Solving real-world problems
  author: Ryan Chang
seo_paginator_message: "page %<current>s of %<total>s | "
