title: ryancyq
description: Solving real-world problems

author:
  name: Ryan Chang

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-postcss
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# theme: minima
# use then latest Minima version instead of bundled version in github pages
remote_theme: jekyll/minima

minima:
  skin: auto
  date_format: "%d-%b-%Y"
  social_links:
    - platform: github
      user_url: https://github.com/ryancyq
    - platform: linkedin
      user_url: https://www.linkedin.com/in/changyanqian/

# Build Settings
timezone: Asia/Singapore
strict_front_matter: true
sass:
  style: compressed
postcss:
  cache: false
markdown: kramdown
highlighter: rouge

# SEO and Site Configuration
google_analytics: G-B3F2H65ZT2
seo:
  title: ryancyq
  description: Solving real-world problems
  author: Ryan Chang