title: ryancyq
description: Solving real-world problems

author:
  name: Ryan Chang

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

nav_pages:
  - blog/index.html

social_links:
  - platform: github
    user_url: https://github.com/ryancyq
  - platform: linkedin
    user_url: https://www.linkedin.com/in/changyanqian/

collections:
  work:
  posts:
    output: false
    permalink: /:collection/:categories/:year/:month/:day/:slug

paginate: 5
paginate_path: "/blog/:num/"

# Build Settings
timezone: Asia/Singapore
date_format: "%d-%b-%Y"
strict_front_matter: true
postcss:
  cache: false
markdown: kramdown
highlighter: rouge

exclude:
  - "*.js"
  - "*.json"

# SEO and Site Configuration
google_analytics: G-B3F2H65ZT2
seo:
  title: ryancyq
  description: Solving real-world problems
  author: Ryan Chang
seo_paginator_message: "page %<current>s of %<total>s | "
